### ISSUE TITLE
Failure to build with go1.12beta1

### ISSUE THREAD

**Issue by mirtchovski** [rjeczalik/notify#169]
Similar to the other issues for go1.10 and go1.11, go 1.12 breaks the build:

```
./watcher_fsevents_cgo.go:51:69: syntax error: unexpected semicolon, expecting expression
```

it appears that go1.11 is still defined, as that file is compiled in, however go1.12 build tag is now available too, if needed. Unfortunately I don't know enough of the core apple lib to help with fixing the issue.

```
$ go list -f '{{ .GoFiles }}'
[debug.go debug_nodebug.go doc.go event.go event_fsevents.go node.go notify.go tree.go tree_nonrecursive.go tree_recursive.go util.go watcher.go watcher_fsevents.go watcher_fsevents_go1.11.go watcher_stub.go watchpoint.go watchpoint_other.go]
```

**Comment by imsodin** [comment]
minio is using an old commit:
```
		{
			"checksumSHA1": "D8AVDI39CJ+jvw0HOotYU2gz54c=",
			"path": "github.com/rjeczalik/notify",
			"revision": "4e54e7fd043e865c50bda93359fb78813a8d165b",
			"revisionTime": "2018-08-08T20:39:25Z"
},
```
This is already fixed, notify builds fine with go1.12

**Comment by mirtchovski** [comment]
Thanks, this is good to know.

**Comment by mirtchovski** [comment]
Hmm. I'm still getting the same failure at tip, macOS 10.14.2, xcode 10.0 (10A255)

```
$ go version
go version devel +e3b4b7baad Tue Dec 18 23:01:06 2018 +0000 darwin/amd64
$ git log -n 1
commit 629144ba06a1c6af28c1e42c228e3d42594ce081 (HEAD -> master, origin/master, origin/HEAD)
Merge: 352c463 8c84b43
Author: Pawel Knap <ppknap@users.noreply.github.com>
Date:   Mon Nov 26 19:32:43 2018 +0100

    Merge pull request #168 from FabianKramm/master
    
    readdcw: Call readdirchangesw if GetQueuedCompletionStatus retrieves zero bytes (Fixes #167)
$ go build
# github.com/rjeczalik/notify
./watcher_fsevents_cgo.go:51:83: syntax error: unexpected semicolon, expecting expression
```

**Comment by rjeczalik** [comment]
From what I learned currently tip should be fixed, so let me close this issue for now.
